In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from tqdm import tqdm
from keras.preprocessing import image
from sklearn.preprocessing import label_binarize
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D
from keras.optimizers import Adam

Importing required libraries

In [2]:
# Read the labels.csv file and checking shape and records
labels_all = pd.read_csv('labels.csv')
labels_all.shape
labels_all.head()

                                 id             breed
0  000bec180eb18c7604dcecc8fe0dba07       boston_bull
1  001513dfcb2ffafc82cccf4d8bbaba97             dingo
2  001cdf01b096e06d78e9e5112d419397          pekinese
3  00214f311d5d2247d5dfe4fe24b2303d          bluetick
4  0021f9ceb3235effd7fcde7f7538ed62  golden_retriever

Loading the labels data into dataframe and viewing it . Here we analyze that labels contain 10222 rows and 2 columns

In [3]:
# Visualize the number of each breed
breeds_all = labels_all['breed']
breeds_counts = breeds_all.value_counts()
breeds_counts.head()

breed
scottish_deerhound      126
maltese_dog             117
afghan_hound            116
entlebucher             115
bernese_mountain_dog    114
Name: count, dtype: int64

Finding out the count per class i.e. total data in each class using the value_counts() function

In [4]:
# Selecting first 3 breeds
CLASS_NAMES = ['scottish_deerhound', 'maltest_dog', 'bernese_mountain_dog']
labels = labels_all[(labels_all['breed'].isin(CLASS_NAMES))]
labels = labels.reset_index()
labels.head()

   index                                id                 breed
0      9  0042188c895a2f14ef64a918ed9c7b64    scottish_deerhound
1     79  01e787576c003930f96c966f9c3e1d44    scottish_deerhound
2    118  02d54f0dfb40038765e838459ae8c956  bernese_mountain_dog
3    161  03dc61595ad9dbf49e3998cf586ca8cb    scottish_deerhound
4    165  03e1d2ee5fd90aef036c90a9e7f81177  bernese_mountain_dog

In [5]:
# Creating numpy matrix with zeros
X_data = np.zeros ((len(labels), 224, 224, 3), dtype='float32')
# One hot encoding
Y_data = label_binarize(labels[ 'breed'], classes = CLASS_NAMES)

# Reading and converting image to numpy array and normalizing dataset
for i in tqdm(range(len(labels))):
    img = image. load_img( 'train/%s.jpg' % labels['id'][i], target_size=(224, 224))
    img = image. img_to_array(img)
    x = np.expand_dims(img.copy(), axis=0)
    X_data [i] = x / 255.0
# Printing train image and one hot encode shape & size
print('\nTrain Images shape: ',X_data.shape,' size: {:,}'. format(X_data.size))
print('One-hot encoded output shape: ',Y_data.shape,' size: {:,}'.format(Y_data.size))

100%|██████████| 240/240 [00:00<00:00, 1120.89it/s]

Train Images shape:  (240, 224, 224, 3)  size: 36,126,720
One-hot encoded output shape:  (240, 3)  size: 720